% Auto-generated by cameraCalibrator app on 02-May-2016
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\Administrator\Documents\美图图库\美图拍拍图库\新建文件夹\meitu_00002.jpg',...
    'C:\Users\Administrator\Documents\美图图库\美图拍拍图库\新建文件夹\meitu_00003.jpg',...
    'C:\Users\Administrator\Documents\美图图库\美图拍拍图库\新建文件夹\meitu_00009.jpg',...
    'C:\Users\Administrator\Documents\美图图库\美图拍拍图库\新建文件夹\meitu_00011.jpg',...
    'C:\Users\Administrator\Documents\美图图库\美图拍拍图库\新建文件夹\meitu_00014.jpg',...
    'C:\Users\Administrator\Documents\美图图库\美图拍拍图库\新建文件夹\meitu_00022.jpg',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 25;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);
worldPoints=worldPoints';
%B=[-38.9493683006338;-5.41768684981463];
B=[0;0];
worldPoints=bsxfun(@minus, worldPoints, B);
worldPoints=worldPoints';
 

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', true, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm', ...
    'InitialIntrinsicMatrix', [437.269445799111,0,0;0.770343963741081,439.131608742382,0;358.981916987229,282.175615014513,1], 'InitialRadialDistortion', [-0.417724999544268,0.181203053402294]);

% View reprojection errors
%h1=figure; showReprojectionErrors(cameraParams,'patternCentric');

% Visualize pattern locations
h2=figure; 
showExtrinsics(cameraParams, 'PatternCentric');

%distortedPoints = vision.internal.calibration.distortPoints([0,0], IntrinsicMatrix,  RadialDistortion,TangentialDistortion);


% Display parameter estimation errors
%displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
%originalImage = imread(imageFileNames{2});
%[undistortedImage,newOrigin]= undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
